name: Forge Gas Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundry-rs/foundry:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run forge gas tests
      run: forge test --gas-report
