name: Forge Gas Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/foundry-rs/foundry:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print working directory
      run: pwd

    - name: List directory content
      run: ls -la

    - name: Check SOLC version
      run: solc --version
      
    - name: Check forge version
      run: forge --version


    - name: Run forge gas tests
      run: forge test --gas-report

    
